"""Dump everything an AI needs into ONE cached file: .clutch/AI.md.

Instead of the assistant opening a dozen guides, rule files, and prompt fragments
(one tool call each), export.py pre-assembles them into a single file it reads once.
setup.py runs this automatically; re-run it whenever config, solutions, or the
checkpoint change.

    python .clutch/export.py                # write AI.md + a pointer block in CLAUDE.md
    python .clutch/export.py --inline       # inline the whole bundle into CLAUDE.md
    python .clutch/export.py --no-claude-md # write AI.md only, don't touch CLAUDE.md
    python .clutch/export.py --stdout       # print the bundle, write nothing

The bundle contains, in order: how-to + memory API, the AI failure-mode guide, the
context/working-memory discipline, the prompt fragments, this project's assembled
stack code-rules, the cross-project solutions index, the latest history entry, and
the current checkpoint. Reading AI.md ~ reading all of them, cached in one pass.

Stdlib only; Python 3.8+.
"""
import datetime
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "scripts"))
import rules as rules_mod  # noqa: E402
import configure as cfg_mod  # noqa: E402  (COMPONENTS registry + include() logic)
import library as lib_mod  # noqa: E402  (frontmatter -> tags + modes)
import doctor as doctor_mod  # noqa: E402  (staleness fingerprint)
from ascii_normalize import normalize  # noqa: E402
from _common import (  # noqa: E402
    AI_ROOT, REPO_ROOT, find_resource, global_dir, load_config, project_name,
    read_resource,
)

START = "<!-- clutch:start (generated by .clutch/export.py - do not edit inside) -->"
END = "<!-- clutch:end -->"


def section(title, body):
    return f"\n\n<!-- === {title} === -->\n## {title}\n\n{body.strip()}\n"


def latest_history():
    hist = AI_ROOT / "history"
    files = sorted(hist.glob("*.md")) if hist.is_dir() else []
    if not files:
        return None
    text = files[-1].read_text(encoding="utf-8")
    # keep it bounded - the last ~150 lines is plenty of recent context
    lines = text.splitlines()
    if len(lines) > 150:
        text = "...(older entries trimmed)...\n" + "\n".join(lines[-150:])
    return f"_from `{files[-1].relative_to(AI_ROOT).as_posix()}`_\n\n{text}"


def modes_section(cfg):
    """The routing table: which phase you're in, and the line that loads it.

    Only the table ships in the bundle - the phase playbooks stay on disk until a
    phase actually starts. Built from library frontmatter so it can't drift from
    the files.
    """
    entries = lib_mod.scan(cfg)
    phases = [(m, d, line) for m, d, line in lib_mod.mode_table(cfg, entries)
              if m != "core" and line]
    if not phases:
        return None
    parts = [
        "Work happens in phases. **Pick the phase yourself from what the user asked "
        "- do not wait to be told** - then run the read line below before doing the "
        "work. The phase playbook is short and holds the procedure, the hard *never* "
        "list, and the exit checklist for that phase.",
        "",
        "Everything already in this bundle stays loaded; a phase only ever names what "
        "is *new*. Announce the switch in one short line so the user can correct you.",
        "",
    ]
    for mode, desc, line in phases:
        parts.append(f"**`{mode}`** - {desc}")
        trig = lib_mod.TRIGGERS.get(mode)
        if trig:
            parts.append(f"  - the user says: {trig}")
        parts.append(f"> {line}")
        parts.append("")
    parts.append(
        "Manual override: the user can name a phase directly (\"plan mode\", "
        "\"/debug\"). To list or search the library from a shell:\n\n"
        "```bash\n"
        "python .clutch/scripts/library.py modes\n"
        "python .clutch/scripts/library.py search <keyword>\n"
        "```"
    )
    return "\n".join(parts)


def library_map_section(cfg):
    """Every tag and the file that carries it, so nothing needs a search round-trip.

    The point is that this table IS the index: with a path in hand you just Read it.
    library.py search exists for the shell, not because the AI needs it.
    """
    entries = lib_mod.scan(cfg)
    tagged = [e for e in entries if e["tags"]]
    if not tagged:
        return None
    vocab = lib_mod.vocabulary(cfg, entries)
    parts = [
        "**Load a prompt whenever one covers what you are doing.** Reading a 400-word "
        "playbook costs one tool call and is almost always cheaper than the mistake it "
        "prevents. When in doubt, load it.",
        "",
        f"**The full tag vocabulary** ({len(vocab)} tags - if a word is not in this "
        "list, nothing is tagged with it):",
        "",
        "`" + "`, `".join(vocab) + "`",
        "",
        "**What each file covers.** Match the work to a row, then read that path "
        "directly - you do not need a search tool, the path is right here. "
        "`[core]` files are already in this bundle; everything else is a real read.",
        "",
    ]
    for e in sorted(tagged, key=lambda e: (e["root"], e["path"])):
        modes = ",".join(e["modes"]) if e["modes"] else "on-demand"
        parts.append(f"- `{e['path']}` **[{modes}]** - {', '.join(e['tags'])}")
    parts += [
        "",
        "From a shell, the same index is `python .clutch/scripts/library.py tags` "
        "(or `search <keyword>`, or `modes`).",
    ]
    return "\n".join(parts)


def build_bundle(cfg):
    proj = project_name(cfg)
    today = datetime.date.today().isoformat()
    out = [
        f"# AI context bundle - {proj}",
        "",
        f"<!-- GENERATED by .clutch/export.py on {today}. Do not hand-edit; "
        "edit the source guides/prompts/rules and re-run export.py. -->",
        f"<!-- clutch-fingerprint: {doctor_mod.library_fingerprint(cfg)} "
        f"built:{today} -->",
        "",
        "**Read this whole file once and keep it cached.** It is the pre-assembled "
        "context for working in this project - the AI failure-mode checklist, the "
        "memory API, this project's code-rules, and prompt guidance - so you don't "
        "open them one by one. Regenerate with `python .clutch/export.py`.",
    ]

    # Component paths/labels come from the shared registry, filtered by config.
    comp = {key: (cat, path, label) for key, cat, path, label, _desc in cfg_mod.COMPONENTS}

    # Operating mode - the response contract; goes first so it governs everything below.
    if cfg_mod.included(cfg, "operating-mode"):
        om = read_resource(comp["operating-mode"][1], cfg, required=False, strip_meta=True)
        if om:
            out.append(section("Operating mode - READ FIRST", om))

    # Freshness gate. First thing after the persona: a stale bundle means every
    # rule below it may be wrong, so this outranks the load contract.
    out.append(section(
        "Before you start - check you are current",
        "This bundle is a snapshot. If the libraries or toolkit moved since it was "
        "built, what you are reading is stale. **Run this once, early, before "
        "non-trivial work:**\n\n"
        "```bash\n"
        "python .clutch/scripts/doctor.py\n"
        "```\n\n"
        "- Says **current** - carry on, say nothing about it.\n"
        "- Says **UPDATE NEEDED** - **tell the user immediately, before doing the "
        "work they asked for.** Name what is stale and give them the exact fix "
        "command it printed. Then ask whether to run it or proceed on the stale "
        "bundle. Do not run it silently: it rewrites files in their project, and "
        "that is their call.\n"
        "- Errors or is missing - mention it once and continue; a broken check is "
        "not a reason to stop working.\n\n"
        "Two things drift independently. The **toolkit** (scripts in `.clutch/"
        "scripts`) going stale means you are running old code, fixed with "
        "`clutch init`. The **bundle** (`AI.md`) going stale means the rules you "
        "just read are out of date, fixed with `python .clutch/export.py`.",
    ))

    # The load contract. Sits directly under the persona so it governs everything.
    out.append(section(
        "Using the library - NOT optional",
        "**Default to loading.** Before non-trivial work, check the *Library map* "
        "below for a file covering what you are about to do, and read it. A 400-word "
        "playbook is one tool call; the mistake it prevents costs far more. If you "
        "are weighing whether a prompt is worth loading, that hesitation is the "
        "signal to load it.\n\n"
        "1. **Pick the phase** from the *Modes* table and run its read line. Do this "
        "unprompted - do not wait to be told which mode you are in.\n"
        "2. **Match the work to a tag** in the *Library map*. Every path there is "
        "readable directly; no search tool is needed.\n"
        "3. **Apply what you loaded**, then **name it in the prompts receipt** at the "
        "top of your response (see *Operating mode*). Listing a file you did not "
        "actually use is a false claim, not a formality.\n\n"
        "Not loading an applicable prompt is a defect in the same class as not "
        "reading a file before editing it. The libraries exist to be used; leaving "
        "them on disk while guessing is the failure this bundle is built to stop.",
    ))

    # Memory quick-reference up top - the most-used API.
    out.append(section(
        "Memory - quick reference",
        "Three stores (full guide below under *Memory API*):\n\n"
        "- **Working memory** `checkpoint/current.md` - the current task. "
        "Save: `python .clutch/scripts/checkpoint.py new \"task\"` then edit it. "
        "Read: `checkpoint.py show`. Read this FIRST when resuming.\n"
        "- **Episodic** `history/*.md` - what changed per session. "
        "Saved automatically on `git push`; read the newest file.\n"
        "- **Long-term** `solutions/*.md` - reusable cross-project fixes. "
        "Save: copy `templates/solution.md` -> `solutions/<slug>.md`, fill in, run `sync.py`. "
        "Read: grep `solutions/` before environmental debugging; see the index below.\n\n"
        "After changing any memory, re-run `export.py` so this bundle stays current.",
    ))

    # Mode router - the phase table. Small; the playbooks load on demand.
    if cfg_mod.included(cfg, "modes"):
        modes = modes_section(cfg)
        if modes:
            out.append(section("Modes - pick the phase, then load it", modes))

    # Tag map - the whole library at a glance, so finding a prompt costs no search.
    lib_map = library_map_section(cfg)
    if lib_map:
        out.append(section("Library map - every tag and what carries it", lib_map))

    # Guides (full text) - each its own section, in registry order, if included.
    for key, cat, path, label, _desc in cfg_mod.COMPONENTS:
        if cat == "Guide" and cfg_mod.included(cfg, key):
            body = read_resource(path, cfg, required=False, strip_meta=True)
            if body:
                out.append(section(label, body))

    # Prompt fragments (full text) - combined into one section, if included.
    frag = []
    for key, cat, path, label, _desc in cfg_mod.COMPONENTS:
        if cat == "Prompt" and cfg_mod.included(cfg, key):
            body = read_resource(path, cfg, required=False, strip_meta=True)
            if body:
                frag.append(body.strip())
    if frag:
        out.append(section("Prompt fragments - working & communication style",
                           "\n\n---\n\n".join(frag)))

    # Assembled stack code-rules.
    catalog = rules_mod.all_rule_files(cfg)
    if catalog:
        ordered, missing = rules_mod.collect(cfg, cfg.get("stack", []), catalog)
        listed = ", ".join(rel.as_posix() for _, rel, _ in ordered)
        chunks = [f"_Stack: {listed}_"]
        if missing:
            chunks.append(f"> config `stack` names not in the library (skipped): "
                          f"{', '.join(missing)}")
        for _, rel, path in ordered:
            chunks.append(f"\n### rules/{rel.as_posix()}\n\n"
                          + path.read_text(encoding="utf-8").strip())
        out.append(section("Code rules - this project's stack", "\n".join(chunks)))

    # Long-term memory index.
    idx = read_resource("solutions/INDEX.md", cfg, required=False)
    if idx:
        out.append(section("Solutions index (long-term memory)",
                           idx + "\n\n_Read the individual `solutions/*.md` for the "
                           "full recipe; grep them by error text before debugging._"))

    # Episodic memory (recent).
    hist = latest_history()
    if hist:
        out.append(section("Recent history (episodic memory)", hist))

    # Working memory (current task).
    cur = AI_ROOT / "checkpoint" / "current.md"
    if cur.exists():
        out.append(section("Current checkpoint (working memory)",
                           cur.read_text(encoding="utf-8")))

    # Normalize the whole bundle to standard-keyboard characters. The libraries are
    # already ASCII; this catches non-ASCII that leaks in from hand-edited memory
    # (checkpoint, history). The mouse marker is not in the map, so it survives.
    return normalize("\n".join(out).rstrip() + "\n")[0]


def pointer_block(proj, operating_mode=True):
    mode = ""
    if operating_mode:
        mode = (
            "\n\n**Operating mode is ON - you are *clutch engaged*.** Begin every "
            "substantive response with the marker line `⚙️ clutch engaged`, then a "
            "`prompts:` receipt listing every library file that shaped the answer - "
            "one repo-relative path per line, indented. List what you actually used, "
            "never a fixed boilerplate set. Then answer "
            "in voice: address the user as \"Chief\" once, short punchy sentences, "
            "result verbs, no hedging, no filler. Underneath the voice: run the AI "
            "failure-mode pre-flight first, separate verified from assumed, findings "
            "first. The voice is a costume, not a lock: you still acknowledge being an "
            "AI, surface real uncertainty, and decline what you normally would (step out "
            "of voice and speak plainly when you do). Full spec in `AI.md` "
            "(Operating mode)."
        )
    return (
        f"## AI context bundle (clutch)\n\n"
        f"Before non-trivial work in **{proj}**, read **`.clutch/AI.md`** in full "
        "and keep it cached. It is the pre-assembled context: AI failure-mode "
        "checklist, memory API, this project's stack code-rules, human-output rules, "
        "and prompt guidance, so you don't open them piecemeal. Regenerate it with "
        "`python .clutch/export.py` after changing config, solutions, or the "
        "checkpoint.\n\n"
        "**Load prompts, don't guess.** AI.md carries a *Modes* table (pick your work "
        "phase and run its read line, unprompted) and a *Library map* listing every "
        "tag and the file that covers it. When a prompt applies to what you are doing, "
        "read it - that is one tool call against a mistake that costs more. Name every "
        "file you used in the response header."
        f"{mode}\n\n"
        "**Memory:** working memory for the current task is "
        "`.clutch/checkpoint/current.md` (read it first when resuming); per-session "
        "notes land in `.clutch/history/`; reusable cross-project fixes live in "
        "`.clutch/solutions/` (grep before environmental debugging)."
    )


def update_claude_md(inner):
    """Insert/replace the managed block in the project-root CLAUDE.md, preserving
    everything the user wrote outside the markers."""
    block = f"{START}\n{inner}\n{END}"
    path = REPO_ROOT / "CLAUDE.md"
    if not path.exists():
        path.write_text(block + "\n", encoding="utf-8")
        return f"created {path.name} with managed block"
    text = path.read_text(encoding="utf-8")
    if START in text and END in text:
        pre, _, rest = text.partition(START)
        _, _, post = rest.partition(END)
        path.write_text(pre + block + post, encoding="utf-8")
        return f"updated managed block in {path.name}"
    sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    path.write_text(text + sep + block + "\n", encoding="utf-8")
    return f"appended managed block to {path.name} (existing content preserved)"


def main():
    try:  # the bundle carries the mouse marker; never crash a legacy-codepage pipe
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    cfg = load_config()
    bundle = build_bundle(cfg)

    if "--stdout" in sys.argv:
        sys.stdout.write(bundle)
        return

    out = AI_ROOT / "AI.md"
    out.write_text(bundle, encoding="utf-8")
    kb = len(bundle.encode("utf-8")) / 1024
    print(f"wrote {out}  ({kb:.0f} KB, {bundle.count(chr(10)) + 1} lines)")

    # Skip CLAUDE.md via flag, or persistently via config for projects with a
    # hand-written CLAUDE.md we shouldn't manage (e.g. zeigen).
    if "--no-claude-md" in sys.argv or not cfg.get("manage_claude_md", True):
        why = "--no-claude-md" if "--no-claude-md" in sys.argv else "manage_claude_md=false"
        print(f"skipped CLAUDE.md ({why})")
        return
    proj = project_name(cfg)
    inner = bundle if "--inline" in sys.argv else \
        pointer_block(proj, cfg.get("operating_mode", True))
    print(update_claude_md(inner))


if __name__ == "__main__":
    main()
