"""Assemble the stack-specific code rules for this project into one RULES.md.

The rules library (languages/frameworks/databases/testing/devops + the always-on
ai/ set) lives in the global store, with a local fallback. This project's stack is
declared in config.json:

    "stack": ["python", "fastapi", "postgresql", "pytest"]

Names match a rule file's stem anywhere in the library (so "fastapi" resolves
frameworks/backend/fastapi.md). The ai/ set is always included.

    python .clutch/scripts/rules.py            # write RULES.md from config stack
    python .clutch/scripts/rules.py --list     # list everything in the library
    python .clutch/scripts/rules.py python react   # ad-hoc, ignore config stack

Writes .clutch/RULES.md - a single file to drop into CLAUDE.md / Cursor rules.
"""
import sys

from _common import AI_ROOT, global_dir, load_config, project_name


def library_dirs(cfg):
    """Search global store first (canonical), then the local rules/ fallback."""
    dirs = []
    g = global_dir(cfg) / "rules"
    if g.is_dir():
        dirs.append(g)
    local = AI_ROOT / "rules"
    if local.is_dir():
        dirs.append(local)
    return dirs


def all_rule_files(cfg):
    """Map stem -> path, first library to define a stem wins."""
    found = {}
    for base in library_dirs(cfg):
        for path in sorted(base.rglob("*.md")):
            if path.name in ("LIBRARY.md", "README.md"):
                continue
            rel = path.relative_to(base)
            found.setdefault(path.stem, (rel, path))
    return found


def collect(cfg, requested, catalog=None):
    """Return (ordered, missing): the ai/ set always on, then the requested stack.

    ordered is a list of (stem, rel, path); missing is the unresolved names.
    Shared by rules.py (writes RULES.md) and export.py (inlines into AI.md).
    """
    catalog = catalog if catalog is not None else all_rule_files(cfg)
    always = [stem for stem, (rel, _) in catalog.items() if rel.parts[0] == "ai"]
    picked, missing = resolve(requested, catalog)
    seen, ordered = set(), []
    for stem in always:
        if stem not in seen:
            seen.add(stem)
            ordered.append((stem, *catalog[stem]))
    for item in picked:
        if item[0] not in seen:
            seen.add(item[0])
            ordered.append(item)
    return ordered, missing


def resolve(names, catalog):
    picked, missing = [], []
    for name in names:
        stem = name.strip().rsplit("/", 1)[-1].removesuffix(".md")
        if stem in catalog:
            picked.append((stem, *catalog[stem]))
        else:
            missing.append(name)
    return picked, missing


def main():
    cfg = load_config()
    args = [a for a in sys.argv[1:] if a != "--list"]

    catalog = all_rule_files(cfg)
    if not catalog:
        sys.exit(
            "error: no rules library found. Expected rules/ in the global store "
            f"({global_dir(cfg) / 'rules'}) or locally ({AI_ROOT / 'rules'}). "
            "Run sync.py to publish the library globally."
        )

    if "--list" in sys.argv:
        for stem, (rel, _) in sorted(catalog.items(), key=lambda kv: str(kv[1][0])):
            print(f"  {rel}")
        print(f"\n{len(catalog)} rule files available")
        return

    requested = args if args else cfg.get("stack", [])
    ordered, missing = collect(cfg, requested, catalog)

    if missing:
        print(f"warning: not in library, skipped: {', '.join(missing)}", file=sys.stderr)
        print("run  rules.py --list  to see valid names", file=sys.stderr)

    proj = project_name(cfg)
    parts = [
        f"# Code rules - {proj}",
        "",
        "<!-- AUTO-GENERATED by .clutch/scripts/rules.py from config.json "
        '"stack". Do not hand-edit; edit the library and re-run. -->',
        "",
        "Assembled rule sets: " + ", ".join(rel.as_posix() for _, rel, _ in ordered),
        "",
    ]
    for _, rel, path in ordered:
        parts.append(f"\n<!-- from rules/{rel.as_posix()} -->\n")
        parts.append(path.read_text(encoding="utf-8").rstrip())
        parts.append("\n\n---")
    out = AI_ROOT / "RULES.md"
    out.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {out}  ({len(ordered)} rule sets)")
    if not requested:
        print('note: config "stack" is empty - only the ai/ set was included. '
              'Add e.g. "stack": ["python","fastapi"] to config.json.')


if __name__ == "__main__":
    main()
