"""Commit this session's work in transcript order, grouped by what produced it.

Reads the Claude Code transcript (via session_report's parser), walks it in order,
and builds a commit plan: one commit per human request (or chapter), containing the
files that request touched and that are actually changed right now ("ready"). Commits
run in the order the work was done.

    python .clutch/scripts/transcript_commit.py            # print the plan (dry run)
    python .clutch/scripts/transcript_commit.py --commit   # actually commit, in order
    python .clutch/scripts/transcript_commit.py --session 04ce6e3a --commit

Safety:
- Dry run by default. Nothing touches git until you pass --commit.
- Only files that git sees as changed are committed (gitignored/unchanged ones are
  skipped). Changes not attributed to the transcript are left alone and reported.
- Commit messages are derived from the request/chapter, ASCII-normalized, with NO
  co-author or "generated by" trailer (see prompts/human-output.md).

Stdlib only; Python 3.8+.
"""
import argparse
import subprocess
import sys
from pathlib import Path

import session_report as sr
from ascii_normalize import normalize

TRIVIAL = {"continue", "yes", "y", "ok", "okay", "go", "sure", "do it", "yep",
           "yeah", "proceed", "keep going", "next"}


def git(root, *args, check=True):
    p = subprocess.run(["git", "-C", str(root), *args], capture_output=True,
                       text=True, encoding="utf-8", errors="replace")
    if check and p.returncode != 0:
        raise SystemExit(f"git {' '.join(args)} failed:\n{p.stderr.strip()}")
    return p.stdout


def repo_root(start):
    p = subprocess.run(["git", "-C", str(start), "rev-parse", "--show-toplevel"],
                       capture_output=True, text=True, encoding="utf-8", errors="replace")
    if p.returncode != 0:
        raise SystemExit(f"not a git repository: {start}\n"
                         "  run this from inside the project's git repo.")
    return Path(p.stdout.strip()).resolve()


def changed_files(root):
    """Repo-relative posix paths git currently sees as changed (excludes ignored)."""
    out = git(root, "status", "--porcelain")
    files = set()
    for line in out.splitlines():
        if not line.strip():
            continue
        rest = line[3:]
        if " -> " in rest:            # rename: take the destination
            rest = rest.split(" -> ")[-1]
        rest = rest.strip().strip('"')
        files.add(rest)
    return files


def parse_units(path):
    """Ordered work units from the transcript. Each unit is a request (or the session
    start) plus the files edited under it, in order, plus any chapter marker."""
    units = []

    def new_unit(label, kind):
        u = {"label": label, "kind": kind, "chapter": None, "files": []}
        units.append(u)
        return u

    cur = new_unit("(session start)", "start")
    for e in sr.iter_events(path):
        t = e.get("type")
        msg = e.get("message")
        if t == "user":
            origin = e.get("origin") or {}
            c = msg.get("content") if isinstance(msg, dict) else None
            if isinstance(c, str) and not e.get("isMeta") and origin.get("kind") == "human":
                cur = new_unit(c.strip(), "request")
        elif t == "assistant" and isinstance(msg, dict) and isinstance(msg.get("content"), list):
            for b in msg["content"]:
                if not isinstance(b, dict) or b.get("type") != "tool_use":
                    continue
                name, inp = b.get("name"), (b.get("input") or {})
                if name in sr.EDIT_TOOLS:
                    fp = inp.get("file_path")
                    if fp and fp not in cur["files"]:
                        cur["files"].append(fp)
                elif name == sr.CHAPTER_TOOL and not cur["chapter"]:
                    cur["chapter"] = {"title": inp.get("title", ""),
                                      "summary": inp.get("summary", "")}
    return units


def unit_message(u, rels):
    if u["chapter"] and u["chapter"]["title"]:
        msg = u["chapter"]["title"]
    else:
        first = next((ln.strip() for ln in u["label"].splitlines() if ln.strip()), "")
        low = first.lower().strip(" .!?")
        if not first or low in TRIVIAL or len(first.split()) <= 1:
            names = ", ".join(Path(r).name for r in rels[:3])
            msg = f"update {names}" + (" and more" if len(rels) > 3 else "")
        else:
            msg = first
    msg = " ".join(normalize(msg)[0].split())        # ASCII + collapse whitespace
    return (msg[:69] + "...") if len(msg) > 72 else (msg or "update files")


def build_plan(units, changed, root):
    assigned, plan = set(), []
    for u in units:
        rels = []
        for fp in u["files"]:
            try:
                rel = Path(fp).resolve().relative_to(root).as_posix()
            except ValueError:
                continue                              # outside this repo
            if rel in assigned or rel not in changed:
                continue                              # already taken, or not "ready"
            rels.append(rel)
            assigned.add(rel)
        if rels:
            plan.append({"message": unit_message(u, rels), "files": rels,
                         "kind": u["kind"]})
    leftover = sorted(changed - assigned)
    return plan, leftover


def main():
    ap = argparse.ArgumentParser(description="Commit a session's work in transcript order.")
    ap.add_argument("--commit", action="store_true", help="actually commit (default: dry run)")
    ap.add_argument("--session", help="conversation id or prefix (default: newest)")
    ap.add_argument("--claude-dir", help="override the .claude dir")
    ap.add_argument("--project-dir", help="project root (default: current directory)")
    args = ap.parse_args()
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

    root = repo_root(Path(args.project_dir) if args.project_dir else Path.cwd())
    if git(root, "diff", "--name-only", "--diff-filter=U").strip():
        raise SystemExit("repo has unmerged paths - resolve the conflict first.")

    _, files = sr.session_files(args)
    if not files:
        raise SystemExit("no session transcript found for this project (try --session / --list "
                         "via session_report.py).")
    chosen = files[0]
    if args.session:
        m = [p for p in files if p.stem.startswith(args.session)]
        if not m:
            raise SystemExit(f"no session matching '{args.session}'")
        chosen = m[0]

    units = parse_units(chosen)
    changed = changed_files(root)
    if not changed:
        print("nothing changed in the working tree - nothing to commit.")
        return
    plan, leftover = build_plan(units, changed, root)

    print(f"session {chosen.stem[:8]} -> {root}")
    if not plan:
        print("no changed files map to this session's transcript.")
    for i, c in enumerate(plan, 1):
        print(f"\n[{i}] {c['message']}")
        for f in c["files"]:
            print(f"      {f}")
    if leftover:
        print(f"\nnot attributed to the transcript (left uncommitted): {len(leftover)}")
        for f in leftover[:20]:
            print(f"      {f}")

    if not args.commit:
        print(f"\ndry run: {len(plan)} commit(s) planned. Re-run with --commit to apply.")
        return
    if not plan:
        return
    print()
    for i, c in enumerate(plan, 1):
        git(root, "add", "--", *c["files"])
        git(root, "commit", "-m", c["message"])
        print(f"committed [{i}] {c['message']}  ({len(c['files'])} file(s))")
    print(f"\ndone: {len(plan)} commit(s) in transcript order."
          + (f" {len(leftover)} file(s) left uncommitted." if leftover else ""))


if __name__ == "__main__":
    main()
